---
title: "R Notebook"
output: html_notebook
---

Venrock

```{r}
url <- "https://www.venrock.com/team/"
```


```{r}
ppl <- get_people(url, "#team-tiles a")

ppl <- ppl[1:(length(ppl)-1)]

venrock <- data_frame()
for(i in 1:length(ppl)){
  current <- get_bios(url, "#bio p", ppl, "Venrock")
  venrock <- rbind(venrock, current)
}
names(venrock) <- c("text", "name", "firm")

write_csv(venrock, "venrock.csv")
```

Dealing with Bessemer
```{r}

urls <- urls[-6]

bessemer <- data_frame()
for(i in urls){
  current <- html_session(i) %>% 
    html_nodes(".field-item.even p") %>% 
    html_text() %>% 
    data_frame() %>% 
    mutate(name = i, firm = "Bessemer VP")
  message(i)
  bessemer <- rbind(bessemer, current)
}

html_session(urls[1]) %>% 
  html_nodes(".field-item.even p") %>% 
  html_text()

names(bessemer) <- c("text", "name", "firm")

bessemer$name <- gsub(url, "", bessemer$name)

bessemer$name <- gsub("/", "", bessemer$name)

bessemer$name <- gsub("-", " ", bessemer$name)

write_csv(bessemer, "bessemer.csv")
```

